version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    container_name: Play_Node_Mark_I
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 8090:8090
    command: "npm run dev"
    links:
      - mongo
  mongo:
    container_name: Play_Mongo_Mark_I
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
